"""为数据库表和字段补充中文 DDL 注释。"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "20260604_0012"
down_revision = "20260530_0011"
branch_labels = None
depends_on = None


SCHEMA = "public"


TABLE_COLUMNS = {
    "agent_analysis_items": [
        "agent_analysis_item_id",
        "agent_run_id",
        "run_id",
        "asset_id",
        "symbol",
        "market",
        "agent_name",
        "stance",
        "confidence",
        "key_points",
        "risk_ids",
        "evidence_ids",
        "summary",
        "as_of",
        "payload",
    ],
    "agent_analysis_runs": [
        "agent_run_id",
        "run_id",
        "agent_name",
        "agent_role",
        "model",
        "model_version",
        "input_ref",
        "input_summary",
        "output_summary",
        "status",
        "started_at",
        "finished_at",
        "latency_ms",
        "error_message",
        "payload",
    ],
    "agent_workflow_events": [
        "workflow_event_id",
        "workflow_run_id",
        "event_type",
        "agent_name",
        "message",
        "evidence_ids",
        "created_at",
        "payload",
    ],
    "agent_workflow_runs": [
        "workflow_run_id",
        "owner_id",
        "workflow_type",
        "trigger_type",
        "trigger_ref",
        "status",
        "started_at",
        "finished_at",
        "input_ref",
        "output_ref",
        "payload",
    ],
    "asset_profiles": [
        "asset_id",
        "source",
        "name",
        "market",
        "symbol",
        "exchange",
        "sector",
        "industry",
        "concept",
        "as_of",
        "payload",
        "created_at",
        "updated_at",
    ],
    "asset_provider_mappings": [
        "mapping_id",
        "asset_id",
        "market",
        "symbol",
        "provider",
        "provider_symbol",
        "provider_exchange",
        "source",
        "status",
        "payload",
        "created_at",
        "updated_at",
    ],
    "asset_recommendations": [
        "recommendation_id",
        "run_id",
        "asset_id",
        "symbol",
        "name",
        "market",
        "horizon",
        "action",
        "rank",
        "total_score",
        "confidence",
        "conviction",
        "score_id",
        "factor_frame_id",
        "signal_ids",
        "risk_ids",
        "agent_analysis_item_ids",
        "evidence_ids",
        "watch_conditions",
        "invalid_if",
        "summary",
        "created_at",
        "payload",
    ],
    "asset_scores": [
        "score_id",
        "asset_id",
        "symbol",
        "market",
        "universe_id",
        "screening_id",
        "factor_frame_id",
        "horizon",
        "total_score",
        "technical_score",
        "fundamental_score",
        "valuation_score",
        "flow_score",
        "derivatives_score",
        "event_score",
        "risk_penalty",
        "rank",
        "rank_in_universe",
        "confidence",
        "missing_penalty",
        "rule_version",
        "status",
        "as_of",
        "payload",
    ],
    "asset_status_snapshots": [
        "asset_id",
        "as_of",
        "source",
        "symbol",
        "market",
        "tradable",
        "trading_status",
        "reason",
        "payload",
        "created_at",
    ],
    "asset_theses": [
        "thesis_id",
        "asset_id",
        "owner_id",
        "source_type",
        "source_id",
        "thesis",
        "supporting_points",
        "risk_points",
        "invalid_if",
        "status",
        "created_at",
        "updated_at",
        "payload",
    ],
    "asset_universe_members": [
        "id",
        "universe_id",
        "asset_id",
        "symbol",
        "market",
        "included",
        "removed_reason",
        "rank_hint",
        "as_of",
        "payload",
    ],
    "asset_universes": [
        "universe_id",
        "name",
        "source",
        "market",
        "strategy_context",
        "owner_id",
        "visibility",
        "base_universe_id",
        "total_before_filter",
        "total_after_filter",
        "filters",
        "status",
        "as_of",
        "created_at",
        "payload",
    ],
    "assets": [
        "asset_id",
        "symbol",
        "name",
        "market",
        "asset_type",
        "exchange",
        "currency",
        "sector",
        "base_asset",
        "quote_asset",
        "tradable",
        "status",
        "payload",
        "created_at",
        "updated_at",
    ],
    "assistant_chat_messages": [
        "chat_message_id",
        "chat_session_id",
        "owner_id",
        "sequence_no",
        "role",
        "content",
        "intent",
        "data",
        "created_at",
        "payload",
    ],
    "assistant_chat_sessions": [
        "chat_session_id",
        "owner_id",
        "title",
        "status",
        "started_at",
        "last_message_at",
        "message_count",
        "summary",
        "created_at",
        "updated_at",
        "payload",
    ],
    "assistant_memories": [
        "memory_id",
        "owner_id",
        "memory_type",
        "scope",
        "asset_id",
        "source_decision_id",
        "source_review_task_id",
        "content",
        "embedding_ref",
        "confidence",
        "status",
        "created_at",
        "updated_at",
        "payload",
    ],
    "assistant_trigger_events": [
        "trigger_event_id",
        "owner_id",
        "trigger_type",
        "trigger_ref",
        "dedup_key",
        "severity",
        "status",
        "agent_runtime",
        "agent_task_id",
        "requested_workflow_type",
        "portfolio_id",
        "watchlist_id",
        "recommendation_run_id",
        "asset_id",
        "cooldown_until",
        "triggered_at",
        "dispatched_at",
        "payload",
    ],
    "capital_flow_snapshots": [
        "snapshot_id",
        "asset_id",
        "symbol",
        "market",
        "main_net_inflow",
        "northbound_net_inflow",
        "turnover_rate",
        "amount",
        "window",
        "source",
        "status",
        "as_of",
        "payload",
    ],
    "crypto_derivative_snapshots": [
        "asset_id",
        "as_of",
        "source",
        "snapshot_id",
        "symbol",
        "market",
        "funding_rate",
        "next_funding_time",
        "open_interest",
        "open_interest_value",
        "long_short_ratio",
        "basis_rate",
        "liquidation_risk_score",
        "status",
        "payload",
        "created_at",
    ],
    "data_quality_snapshots": [
        "quality_id",
        "asset_id",
        "symbol",
        "market",
        "data_domain",
        "provider",
        "status",
        "freshness_status",
        "latest_data_at",
        "checked_at",
        "missing_items",
        "issue_count",
        "payload",
    ],
    "decision_logs": [
        "decision_id",
        "owner_id",
        "portfolio_id",
        "asset_id",
        "decision_type",
        "source_recommendation_id",
        "source_alert_id",
        "workflow_run_id",
        "suggested_action",
        "user_action",
        "summary",
        "reason_ids",
        "risk_ids",
        "evidence_ids",
        "created_at",
        "payload",
    ],
    "event_records": [
        "event_id",
        "asset_id",
        "symbol",
        "market",
        "event_type",
        "title",
        "summary",
        "sentiment",
        "importance",
        "source",
        "url",
        "published_at",
        "collected_at",
        "payload",
    ],
    "evidence": [
        "evidence_id",
        "evidence_type",
        "asset_id",
        "source",
        "title",
        "summary",
        "data_ref",
        "url",
        "reliability",
        "as_of",
        "collected_at",
        "payload",
    ],
    "factor_frames": [
        "factor_frame_id",
        "asset_id",
        "symbol",
        "market",
        "horizon",
        "status",
        "total_available_groups",
        "missing_groups",
        "source_ids",
        "indicator_frame_id",
        "as_of",
        "payload",
    ],
    "financial_memory_edges": [
        "edge_id",
        "owner_id",
        "source_type",
        "source_id",
        "relation_type",
        "target_type",
        "target_id",
        "confidence",
        "reason",
        "created_at",
        "payload",
    ],
    "fundamental_snapshots": [
        "snapshot_id",
        "asset_id",
        "symbol",
        "report_period",
        "pe_ttm",
        "pb",
        "roe",
        "revenue_growth_yoy",
        "net_profit_growth_yoy",
        "debt_to_asset",
        "operating_cashflow",
        "source",
        "status",
        "missing_fields",
        "as_of",
        "payload",
    ],
    "indicator_frames": [
        "indicator_frame_id",
        "asset_id",
        "symbol",
        "market",
        "timeframe",
        "horizon",
        "library",
        "library_version",
        "input_start_at",
        "input_end_at",
        "bar_count",
        "rsi_14",
        "macd",
        "macd_signal",
        "macd_hist",
        "atr_14",
        "bb_percent_b",
        "ma_20",
        "ma_60",
        "status",
        "as_of",
        "payload",
    ],
    "market_bars": [
        "asset_id",
        "symbol",
        "market",
        "timeframe",
        "timestamp",
        "end_timestamp",
        "open",
        "high",
        "low",
        "close",
        "volume",
        "amount",
        "source",
        "adjustment",
        "is_closed",
        "raw_record_id",
        "status",
        "created_at",
    ],
    "market_calendars": [
        "calendar_id",
        "market",
        "exchange",
        "trade_date",
        "is_trading_day",
        "open_at",
        "close_at",
        "session_type",
        "timezone",
        "status",
        "source",
        "payload",
    ],
    "memory_embeddings": [
        "embedding_id",
        "owner_id",
        "memory_id",
        "source_type",
        "source_id",
        "chunk_text",
        "embedding",
        "embedding_model",
        "content_hash",
        "created_at",
        "payload",
    ],
    "model_instances": [
        "model_instance_id",
        "provider_key",
        "model_key",
        "model_type",
        "model_name",
        "role",
        "route_priority",
        "timeout_seconds",
        "is_enabled",
        "is_default",
        "payload",
        "created_at",
        "updated_at",
    ],
    "model_providers": [
        "provider_id",
        "provider_key",
        "provider_vendor",
        "provider_name",
        "base_url",
        "api_key",
        "timeout_seconds",
        "is_enabled",
        "is_default",
        "payload",
        "created_at",
        "updated_at",
    ],
    "model_routing_rules": [
        "rule_id",
        "workflow_type",
        "task",
        "role",
        "model_key",
        "decision_type",
        "reason",
        "priority",
        "is_enabled",
        "payload",
        "created_at",
        "updated_at",
    ],
    "monitoring_alerts": [
        "alert_id",
        "owner_id",
        "portfolio_id",
        "asset_id",
        "alert_type",
        "severity",
        "triggered_by",
        "trigger_condition",
        "current_value",
        "threshold_value",
        "status",
        "as_of",
        "payload",
    ],
    "portfolio_snapshots": [
        "snapshot_id",
        "portfolio_id",
        "owner_id",
        "total_equity",
        "cash",
        "market_value",
        "position_count",
        "source",
        "captured_at",
        "payload",
    ],
    "portfolios": [
        "portfolio_id",
        "owner_id",
        "name",
        "portfolio_type",
        "base_currency",
        "risk_profile",
        "total_equity",
        "cash",
        "market_value",
        "max_position_weight",
        "max_drawdown_alert",
        "status",
        "as_of",
        "payload",
        "created_at",
        "updated_at",
    ],
    "position_snapshots": [
        "snapshot_id",
        "position_id",
        "portfolio_id",
        "asset_id",
        "symbol",
        "market",
        "side",
        "quantity",
        "avg_cost",
        "last_price",
        "market_value",
        "unrealized_pnl",
        "unrealized_pnl_pct",
        "portfolio_weight",
        "leverage",
        "liquidation_price",
        "source",
        "captured_at",
        "payload",
    ],
    "positions": [
        "position_id",
        "portfolio_id",
        "asset_id",
        "symbol",
        "market",
        "side",
        "quantity",
        "avg_cost",
        "last_price",
        "market_value",
        "unrealized_pnl",
        "unrealized_pnl_pct",
        "portfolio_weight",
        "leverage",
        "liquidation_price",
        "status",
        "as_of",
        "payload",
    ],
    "raw_records": [
        "raw_record_id",
        "provider",
        "endpoint",
        "asset_id",
        "symbol",
        "market",
        "request_params",
        "request_hash",
        "response_payload",
        "content_hash",
        "provider_version",
        "latency_ms",
        "retry_count",
        "status",
        "error_message",
        "as_of",
        "collected_at",
    ],
    "realtime_quote_snapshots": [
        "asset_id",
        "as_of",
        "source",
        "symbol",
        "market",
        "last_price",
        "prev_close",
        "open",
        "high",
        "low",
        "volume",
        "amount",
        "turnover_rate",
        "change_amount",
        "change_percent",
        "bid_price",
        "ask_price",
        "status",
        "payload",
        "created_at",
    ],
    "recommendation_run_universes": [
        "id",
        "run_id",
        "universe_id",
        "market",
        "role",
        "weight",
        "asset_count",
        "payload",
    ],
    "recommendation_runs": [
        "run_id",
        "universe_id",
        "screening_id",
        "strategy",
        "market",
        "horizon",
        "limit",
        "status",
        "started_at",
        "finished_at",
        "summary",
        "payload",
    ],
    "retrieval_profiles": [
        "profile_id",
        "profile_key",
        "profile_name",
        "usage_scope",
        "search_method",
        "embedding_model_key",
        "rerank_model_key",
        "top_k",
        "score_threshold",
        "reranking_enable",
        "reranking_mode",
        "weights",
        "is_enabled",
        "is_default",
        "payload",
        "created_at",
        "updated_at",
    ],
    "review_tasks": [
        "review_task_id",
        "owner_id",
        "asset_id",
        "source_decision_id",
        "review_type",
        "due_at",
        "status",
        "review_questions",
        "result_summary",
        "created_at",
        "finished_at",
        "payload",
    ],
    "risk_findings": [
        "risk_id",
        "asset_id",
        "scope",
        "risk_type",
        "severity",
        "score",
        "title",
        "description",
        "as_of",
        "evidence_ids",
        "payload",
    ],
    "screening_result_items": [
        "screening_item_id",
        "screening_id",
        "universe_id",
        "asset_id",
        "symbol",
        "market",
        "passed",
        "removed_reason",
        "failed_rules",
        "passed_rules",
        "data_status",
        "liquidity_status",
        "as_of",
        "payload",
    ],
    "screening_results": [
        "screening_id",
        "universe_id",
        "strategy",
        "market",
        "passed_count",
        "removed_count",
        "rules",
        "status",
        "as_of",
        "payload",
    ],
    "signal_snapshots": [
        "signal_id",
        "asset_id",
        "symbol",
        "market",
        "horizon",
        "direction",
        "score",
        "confidence",
        "rule_version",
        "status",
        "as_of",
        "payload",
    ],
    "watchlist_item_events": [
        "event_id",
        "owner_id",
        "watchlist_id",
        "watchlist_item_id",
        "asset_id",
        "event_type",
        "from_status",
        "to_status",
        "reason",
        "source_decision_id",
        "created_at",
        "payload",
    ],
    "watchlist_items": [
        "watchlist_item_id",
        "watchlist_id",
        "asset_id",
        "symbol",
        "market",
        "source_type",
        "source_id",
        "reason",
        "watch_conditions",
        "trigger_conditions",
        "invalid_conditions",
        "risk_level",
        "status",
        "next_review_at",
        "created_at",
        "updated_at",
        "removed_at",
        "removed_reason",
        "payload",
    ],
    "watchlists": [
        "watchlist_id",
        "owner_id",
        "name",
        "market",
        "purpose",
        "status",
        "created_at",
        "updated_at",
        "payload",
    ],
}


TABLE_COMMENTS = {
    "agent_analysis_items": "Agent 单标的分析明细表，保存每个分析角色对资产的立场、证据和摘要。",
    "agent_analysis_runs": "Agent 分析运行表，记录推荐流程中各分析角色的模型调用、输入输出和耗时。",
    "agent_workflow_events": "Agent 工作流事件表，按时间记录工作流节点、工具调用和过程消息。",
    "agent_workflow_runs": "Agent 工作流运行表，记录用户触发或系统触发的分析工作流执行状态。",
    "asset_profiles": "资产资料附表，保存资产名称、行业、概念、交易所等相对稳定的扩展信息。",
    "asset_provider_mappings": (
        "资产供应商映射表，保存系统资产与外部数据源代码、市场代码的对应关系。"
    ),
    "asset_recommendations": (
        "资产推荐结果表，保存每次推荐运行产出的标的、动作、分数、证据和观察条件。"
    ),
    "asset_scores": "资产评分表，保存技术、基本面、估值、资金流、事件和风险等维度的综合评分。",
    "asset_status_snapshots": "资产交易状态快照表，记录资产是否可交易、停牌或异常状态。",
    "asset_theses": "资产投资假设表，保存用户或系统沉淀的投资逻辑、支撑点和失效条件。",
    "asset_universe_members": "资产池成员表，保存某个资产池在指定时点包含或剔除的资产。",
    "asset_universes": "资产池主表，保存全市场、指数、行业、概念、自选等资产集合定义。",
    "assets": "资产主表，保存股票、指数、加密货币等资产的核心标识和基本交易属性。",
    "assistant_chat_messages": "助手聊天消息表，保存用户与金融 Agent 的逐轮对话内容和意图结果。",
    "assistant_chat_sessions": "助手聊天会话表，保存对话会话的归属、标题、状态和汇总信息。",
    "assistant_memories": "助手金融记忆表，保存用户偏好、决策复盘、资产观点等长期记忆。",
    "assistant_trigger_events": (
        "助手触发事件表，保存告警、推荐、复盘等事件触发 Agent 工作流的调度记录。"
    ),
    "capital_flow_snapshots": "资金流快照表，保存主力资金、北向资金、换手率和成交额等资金面数据。",
    "crypto_derivative_snapshots": (
        "加密衍生品快照表，保存资金费率、持仓量、多空比和基差等合约数据。"
    ),
    "data_quality_snapshots": "数据质量快照表，保存各资产、数据域和供应商的数据新鲜度与缺失情况。",
    "decision_logs": "用户决策日志表，保存推荐、告警或工作流之后的建议动作和用户最终动作。",
    "event_records": "事件记录表，保存新闻、公告、异动等事件源及其清洗摘要。",
    "evidence": "证据表，保存推荐、评分、风险和 Agent 分析可引用的事实证据。",
    "factor_frames": "因子帧表，保存某资产在指定周期下可用因子组、缺失因子和来源引用。",
    "financial_memory_edges": "金融记忆关系表，保存记忆、决策、资产和事件之间的语义关系。",
    "fundamental_snapshots": "基本面快照表，保存估值、盈利、成长、负债和现金流等财务指标。",
    "indicator_frames": "技术指标帧表，保存由行情 K 线计算得到的 RSI、MACD、ATR、均线等指标。",
    "market_bars": "行情 K 线表，保存资产在不同周期下的 OHLCV、成交额和复权信息。",
    "market_calendars": "交易日历表，保存市场和交易所的交易日、开闭市时间和时区信息。",
    "memory_embeddings": "记忆向量表，保存金融记忆文本分块和向量索引用于相似检索。",
    "model_instances": "模型实例表，保存可调用模型名称、类型、角色、优先级和启用状态。",
    "model_providers": "模型供应商表，保存 OpenAI 兼容供应商、接入端点、密钥和连接配置。",
    "model_routing_rules": "模型路由规则表，保存不同工作流、任务和角色选择模型的策略规则。",
    "monitoring_alerts": "监控告警表，保存组合、资产和风险条件触发的告警记录。",
    "portfolio_snapshots": "组合快照表，保存组合在某一时点的权益、现金、市值和持仓数量。",
    "portfolios": "投资组合主表，保存用户组合、资金、风险配置和当前汇总状态。",
    "position_snapshots": "持仓快照表，保存持仓在某一时点的数量、成本、市值和盈亏。",
    "positions": "持仓表，保存组合当前持仓、成本、价格、权重和盈亏状态。",
    "raw_records": "原始采集记录表，保存外部数据源请求参数、响应原文、状态和错误信息。",
    "realtime_quote_snapshots": "实时行情快照表，保存最新价格、涨跌幅、成交额、买卖价等盘中快照。",
    "recommendation_run_universes": "推荐运行资产池关系表，保存一次推荐运行使用的资产池及权重。",
    "recommendation_runs": "推荐运行表，保存一次策略推荐任务的市场、周期、状态和汇总结果。",
    "retrieval_profiles": "检索配置表，保存向量检索、重排、TopK、阈值和权重等 RAG 配置。",
    "review_tasks": "复盘任务表，保存推荐或决策后的定期回看任务及复盘结果。",
    "risk_findings": "风险发现表，保存趋势破位、数据异常、事件冲击等风险条目。",
    "screening_result_items": "筛选结果明细表，保存单个资产是否通过规则及失败原因。",
    "screening_results": "筛选结果表，保存某个策略在资产池上的筛选汇总和规则。",
    "signal_snapshots": "交易信号快照表，保存资产在指定周期下的方向、分数和置信度。",
    "watchlist_item_events": "观察池条目事件表，保存观察池条目的加入、移除和状态变更历史。",
    "watchlist_items": "观察池条目表，保存用户关注资产、关注理由、触发条件和失效条件。",
    "watchlists": "观察池主表，保存用户不同用途的关注列表定义。",
}


COLUMN_COMMENTS = {
    "action": "推荐动作，如 buy、watch、avoid 等。",
    "adjustment": "行情复权类型，如前复权、后复权或不复权。",
    "agent_analysis_item_id": "Agent 单标的分析明细唯一标识。",
    "agent_analysis_item_ids": "关联的 Agent 分析明细标识列表。",
    "agent_name": "执行分析或产生日志的 Agent 名称。",
    "agent_role": "Agent 在分析流程中的角色定位。",
    "agent_run_id": "Agent 分析运行唯一标识。",
    "agent_runtime": "触发事件期望使用的 Agent 运行时类型。",
    "agent_task_id": "外部或后台 Agent 任务标识。",
    "alert_id": "监控告警唯一标识。",
    "alert_type": "告警类型。",
    "amount": "成交额或业务金额。",
    "api_key": "模型供应商 API Key，按系统安全策略加密或脱敏保存。",
    "as_of": "该条业务数据对应的市场时点或统计时点。",
    "ask_price": "卖一价或最优卖出报价。",
    "asset_count": "资产数量。",
    "asset_id": "系统内资产唯一标识，通常由市场和代码组合生成。",
    "asset_type": "资产类型，如股票、指数、现货或合约。",
    "atr_14": "14 周期 ATR 平均真实波幅指标。",
    "avg_cost": "持仓平均成本。",
    "bar_count": "参与指标计算的 K 线数量。",
    "base_asset": "交易对基础资产。",
    "base_currency": "组合或账户的基准币种。",
    "base_universe_id": "派生资产池对应的基础资产池标识。",
    "base_url": "OpenAI 兼容模型供应商的接入端点。",
    "basis_rate": "合约基差率。",
    "bb_percent_b": "布林带 Percent B 指标。",
    "bid_price": "买一价或最优买入报价。",
    "calendar_id": "交易日历记录唯一标识。",
    "captured_at": "快照捕获时间。",
    "cash": "组合现金余额。",
    "change_amount": "价格涨跌额。",
    "change_percent": "价格涨跌幅。",
    "chat_message_id": "聊天消息唯一标识。",
    "chat_session_id": "聊天会话唯一标识。",
    "checked_at": "数据质量检查时间。",
    "chunk_text": "用于向量化的文本分块内容。",
    "close": "收盘价。",
    "close_at": "交易时段收市时间。",
    "collected_at": "数据采集入库时间。",
    "concept": "资产所属概念或概念板块。",
    "confidence": "置信度，通常取值 0 到 1。",
    "content": "正文内容。",
    "content_hash": "内容哈希，用于去重和版本识别。",
    "conviction": "推荐确信度分层，如 low、medium、high。",
    "cooldown_until": "触发事件冷却结束时间。",
    "created_at": "记录创建时间。",
    "currency": "交易或计价货币。",
    "current_value": "触发告警时的当前值。",
    "data": "结构化业务数据。",
    "data_domain": "数据域，如行情、基本面、资金流、事件、风险等。",
    "data_ref": "证据指向的数据引用。",
    "data_status": "数据可用性状态。",
    "debt_to_asset": "资产负债率。",
    "decision_id": "决策日志唯一标识。",
    "decision_type": "决策类型。",
    "dedup_key": "事件去重键。",
    "derivatives_score": "衍生品维度评分。",
    "description": "详细说明。",
    "direction": "信号方向，如 bullish、bearish、mixed。",
    "dispatched_at": "事件派发时间。",
    "due_at": "复盘任务到期时间。",
    "edge_id": "记忆关系唯一标识。",
    "embedding": "向量嵌入数据。",
    "embedding_id": "向量记录唯一标识。",
    "embedding_model": "生成向量所使用的模型。",
    "embedding_model_key": "检索配置使用的向量模型键。",
    "embedding_ref": "外部向量索引或嵌入引用。",
    "end_timestamp": "K 线结束时间。",
    "endpoint": "外部数据源接口名称或路径。",
    "error_message": "失败或异常信息。",
    "event_id": "事件唯一标识。",
    "event_score": "事件维度评分。",
    "event_type": "事件类型。",
    "evidence_id": "证据唯一标识。",
    "evidence_ids": "关联证据标识列表。",
    "evidence_type": "证据类型。",
    "exchange": "交易所。",
    "factor_frame_id": "因子帧唯一标识。",
    "failed_rules": "未通过的筛选规则列表。",
    "filters": "资产池过滤条件。",
    "finished_at": "运行或任务结束时间。",
    "flow_score": "资金流维度评分。",
    "freshness_status": "数据新鲜度状态。",
    "from_status": "状态变更前状态。",
    "fundamental_score": "基本面维度评分。",
    "funding_rate": "合约资金费率。",
    "high": "最高价。",
    "horizon": "策略观察周期，如 swing、intraday。",
    "id": "通用记录唯一标识。",
    "importance": "事件重要性等级或分值。",
    "included": "是否纳入资产池。",
    "indicator_frame_id": "技术指标帧唯一标识。",
    "industry": "资产所属行业。",
    "input_end_at": "指标或模型输入数据结束时间。",
    "input_ref": "工作流或模型输入引用。",
    "input_start_at": "指标或模型输入数据开始时间。",
    "input_summary": "模型或 Agent 输入摘要。",
    "intent": "识别出的用户意图。",
    "invalid_conditions": "观察池条目的失效条件集合。",
    "invalid_if": "推荐或投资假设的失效条件。",
    "is_closed": "K 线是否已收盘确认。",
    "is_default": "是否为默认配置。",
    "is_enabled": "是否启用。",
    "is_trading_day": "是否为交易日。",
    "issue_count": "数据质量问题数量。",
    "key_points": "分析关键观点列表。",
    "last_message_at": "会话最后一条消息时间。",
    "last_price": "最新成交价或最新报价。",
    "latency_ms": "接口或模型调用耗时，单位毫秒。",
    "latest_data_at": "当前数据域最新数据时间。",
    "leverage": "杠杆倍数。",
    "library": "指标计算库名称。",
    "library_version": "指标计算库版本。",
    "limit": "本次任务或推荐返回数量上限。",
    "liquidation_price": "强平价格。",
    "liquidation_risk_score": "强平风险分数。",
    "liquidity_status": "流动性状态。",
    "long_short_ratio": "多空比。",
    "low": "最低价。",
    "ma_20": "20 周期移动平均线。",
    "ma_60": "60 周期移动平均线。",
    "macd": "MACD 差离值。",
    "macd_hist": "MACD 柱状图值。",
    "macd_signal": "MACD 信号线。",
    "main_net_inflow": "主力资金净流入。",
    "mapping_id": "供应商映射唯一标识。",
    "market": "市场标识，如 ashare、crypto_spot、crypto_future。",
    "market_value": "持仓或组合市值。",
    "max_drawdown_alert": "组合最大回撤告警阈值。",
    "max_position_weight": "单一持仓最大权重限制。",
    "memory_id": "金融记忆唯一标识。",
    "memory_type": "记忆类型。",
    "message": "事件或日志消息。",
    "message_count": "会话消息数量。",
    "missing_fields": "缺失字段列表。",
    "missing_groups": "缺失因子组列表。",
    "missing_items": "缺失数据项列表。",
    "missing_penalty": "因数据缺失产生的评分惩罚。",
    "model": "模型名称。",
    "model_instance_id": "模型实例唯一标识。",
    "model_key": "模型键，用于路由和调用。",
    "model_name": "模型展示名称。",
    "model_type": "模型类型，如 chat、embedding、rerank。",
    "model_version": "模型版本。",
    "name": "名称。",
    "net_profit_growth_yoy": "归母净利润同比增长率。",
    "next_funding_time": "下一次资金费率结算时间。",
    "next_review_at": "下一次复核时间。",
    "northbound_net_inflow": "北向资金净流入。",
    "open": "开盘价。",
    "open_at": "交易时段开市时间。",
    "open_interest": "合约未平仓量。",
    "open_interest_value": "合约未平仓金额。",
    "operating_cashflow": "经营活动现金流。",
    "output_ref": "工作流或模型输出引用。",
    "output_summary": "模型或 Agent 输出摘要。",
    "owner_id": "数据所属用户或租户标识。",
    "passed": "是否通过筛选规则。",
    "passed_count": "通过筛选的数量。",
    "passed_rules": "已通过的筛选规则列表。",
    "payload": "扩展 JSON 数据，保存原始字段、计算细节或兼容信息。",
    "pb": "市净率。",
    "pe_ttm": "滚动市盈率。",
    "portfolio_id": "投资组合唯一标识。",
    "portfolio_type": "组合类型。",
    "portfolio_weight": "持仓在组合中的权重。",
    "position_count": "持仓数量。",
    "position_id": "持仓唯一标识。",
    "prev_close": "前收盘价。",
    "priority": "规则或路由优先级。",
    "profile_id": "检索配置唯一标识。",
    "profile_key": "检索配置键。",
    "profile_name": "检索配置名称。",
    "provider": "数据源或服务供应商。",
    "provider_exchange": "供应商侧交易所标识。",
    "provider_id": "模型供应商唯一标识。",
    "provider_key": "模型供应商键。",
    "provider_name": "模型供应商展示名称。",
    "provider_symbol": "供应商侧资产代码。",
    "provider_vendor": "模型供应商厂商类型。",
    "provider_version": "数据源或采集器版本。",
    "published_at": "事件发布时间。",
    "purpose": "观察池用途说明。",
    "quality_id": "数据质量记录唯一标识。",
    "quantity": "持仓数量。",
    "quote_asset": "交易对计价资产。",
    "rank": "排名。",
    "rank_hint": "资产池成员排序提示。",
    "rank_in_universe": "资产在资产池内的排名。",
    "raw_record_id": "原始采集记录唯一标识。",
    "reason": "原因说明。",
    "reason_ids": "关联原因标识列表。",
    "recommendation_id": "资产推荐唯一标识。",
    "recommendation_run_id": "推荐运行唯一标识。",
    "relation_type": "记忆关系类型。",
    "reliability": "证据可靠性等级。",
    "removed_at": "移除时间。",
    "removed_count": "剔除数量。",
    "removed_reason": "剔除原因。",
    "report_period": "财务报告期。",
    "request_hash": "请求参数哈希。",
    "request_params": "外部数据源请求参数。",
    "requested_workflow_type": "请求执行的工作流类型。",
    "rerank_model_key": "重排模型键。",
    "reranking_enable": "是否启用重排。",
    "reranking_mode": "重排模式。",
    "response_payload": "外部数据源响应原文。",
    "result_summary": "复盘或任务结果摘要。",
    "retry_count": "重试次数。",
    "revenue_growth_yoy": "营业收入同比增长率。",
    "review_questions": "复盘问题清单。",
    "review_task_id": "复盘任务唯一标识。",
    "review_type": "复盘类型。",
    "risk_id": "风险条目唯一标识。",
    "risk_ids": "关联风险条目标识列表。",
    "risk_level": "风险等级。",
    "risk_penalty": "风险扣分。",
    "risk_points": "投资假设中的风险点。",
    "risk_profile": "组合风险偏好。",
    "risk_type": "风险类型。",
    "roe": "净资产收益率。",
    "role": "模型或消息角色。",
    "route_priority": "模型路由优先级。",
    "rsi_14": "14 周期 RSI 指标。",
    "rule_id": "规则唯一标识。",
    "rule_version": "评分或信号规则版本。",
    "rules": "筛选规则配置。",
    "run_id": "推荐运行唯一标识。",
    "scope": "适用范围。",
    "score": "分数。",
    "score_id": "资产评分唯一标识。",
    "score_threshold": "检索或重排分数阈值。",
    "screening_id": "筛选运行唯一标识。",
    "screening_item_id": "筛选结果明细唯一标识。",
    "search_method": "检索方法。",
    "sector": "资产所属板块或行业大类。",
    "sentiment": "事件情绪倾向。",
    "sequence_no": "消息在会话中的序号。",
    "session_type": "交易时段类型。",
    "severity": "严重程度。",
    "side": "持仓方向，如 long、short。",
    "signal_id": "交易信号唯一标识。",
    "signal_ids": "关联交易信号标识列表。",
    "snapshot_id": "快照唯一标识。",
    "source": "数据来源。",
    "source_alert_id": "来源告警标识。",
    "source_decision_id": "来源决策日志标识。",
    "source_id": "来源对象标识。",
    "source_ids": "关联来源对象标识列表。",
    "source_recommendation_id": "来源推荐标识。",
    "source_review_task_id": "来源复盘任务标识。",
    "source_type": "来源对象类型。",
    "stance": "Agent 对标的的分析立场。",
    "started_at": "运行或任务开始时间。",
    "status": "业务状态。",
    "strategy": "策略名称。",
    "strategy_context": "资产池或筛选使用的策略上下文。",
    "suggested_action": "系统建议动作。",
    "summary": "摘要说明。",
    "supporting_points": "投资假设中的支撑点。",
    "symbol": "交易代码。",
    "target_id": "关系目标对象标识。",
    "target_type": "关系目标对象类型。",
    "task": "任务名称或任务类型。",
    "technical_score": "技术面维度评分。",
    "thesis": "投资假设正文。",
    "thesis_id": "投资假设唯一标识。",
    "threshold_value": "告警阈值。",
    "timeframe": "行情或指标周期，如 1d、1h。",
    "timeout_seconds": "请求或模型调用超时时间，单位秒。",
    "timestamp": "K 线开始时间或行情时间戳。",
    "timezone": "市场时区。",
    "title": "标题。",
    "to_status": "状态变更后状态。",
    "top_k": "检索返回条数。",
    "total_after_filter": "过滤后资产数量。",
    "total_available_groups": "可用因子组数量。",
    "total_before_filter": "过滤前资产数量。",
    "total_equity": "组合总权益。",
    "total_score": "综合评分。",
    "tradable": "是否可交易。",
    "trade_date": "交易日期。",
    "trading_status": "交易状态。",
    "trigger_condition": "告警触发条件。",
    "trigger_conditions": "观察池触发条件集合。",
    "trigger_event_id": "助手触发事件唯一标识。",
    "trigger_ref": "触发来源引用。",
    "trigger_type": "触发类型。",
    "triggered_at": "触发时间。",
    "triggered_by": "触发来源。",
    "turnover_rate": "换手率。",
    "universe_id": "资产池唯一标识。",
    "unrealized_pnl": "未实现盈亏金额。",
    "unrealized_pnl_pct": "未实现盈亏比例。",
    "updated_at": "记录更新时间。",
    "url": "原始链接。",
    "usage_scope": "检索配置适用范围。",
    "user_action": "用户实际执行动作。",
    "valuation_score": "估值维度评分。",
    "visibility": "资产池可见范围。",
    "volume": "成交量。",
    "watch_conditions": "推荐或观察池关注条件。",
    "watchlist_id": "观察池唯一标识。",
    "watchlist_item_id": "观察池条目唯一标识。",
    "weight": "权重。",
    "weights": "检索或评分权重配置。",
    "window": "统计窗口。",
    "workflow_event_id": "工作流事件唯一标识。",
    "workflow_run_id": "工作流运行唯一标识。",
    "workflow_type": "工作流类型。",
}


def _quote_ident(identifier: str) -> str:
    return '"' + identifier.replace('"', '""') + '"'


def _quote_literal(value: str | None) -> str:
    if value is None:
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def _qualified_table(table_name: str) -> str:
    return f"{_quote_ident(SCHEMA)}.{_quote_ident(table_name)}"


def _comment_on_table(table_name: str, comment: str | None) -> None:
    op.execute(
        sa.text(f"COMMENT ON TABLE {_qualified_table(table_name)} IS {_quote_literal(comment)}")
    )


def _comment_on_column(table_name: str, column_name: str, comment: str | None) -> None:
    op.execute(
        sa.text(
            "COMMENT ON COLUMN "
            f"{_qualified_table(table_name)}.{_quote_ident(column_name)} "
            f"IS {_quote_literal(comment)}"
        )
    )


def _column_comment(table_name: str, column_name: str) -> str:
    return COLUMN_COMMENTS.get(
        column_name,
        f"{TABLE_COMMENTS[table_name]}中的 {column_name} 字段。",
    )


def upgrade() -> None:
    """写入中文表注释和字段注释。"""

    for table_name, columns in TABLE_COLUMNS.items():
        _comment_on_table(table_name, TABLE_COMMENTS[table_name])
        for column_name in columns:
            _comment_on_column(table_name, column_name, _column_comment(table_name, column_name))


def downgrade() -> None:
    """移除本迁移写入的中文表注释和字段注释。"""

    for table_name, columns in reversed(TABLE_COLUMNS.items()):
        for column_name in reversed(columns):
            _comment_on_column(table_name, column_name, None)
        _comment_on_table(table_name, None)
